baseURL = "/"
languageCode = "en-us"
title = "Greprovad"
theme = "kube"
description = "Groupe de Recherche de Prospection et Valorisation des Donn√©es"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Greprovad" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
